apiVersion: 1
#resource https://github.com/grafana/grafana/blob/main/devenv/datasources.yaml
datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: P8E80F9AEF21F6940
    url: http://loki:3100
    editable: true
    correlations:
      - targetUID: P8E80F9AEF21F7000
        label: "Jaeger traces"
        description: "Related traces stored in Jaeger"
      - targetUID: PBFA97CFB590B2093
        label: "Logs to metrics"
        description: "Related metrics stored in Prometheus"
        config:
          type: query
          target:
            expr: "{ exporter=\"OTLP\" }"
          field: "traceID"
    jsonData:
      manageAlerts: false
      derivedFields:
        - name: "traceID"
          matcherRegex: \"traceid\":\"(\w+)
          url: "$${__value.raw}"
          datasourceUid: P8E80F9AEF21F7000

  - name: Jeager
    type: jaeger
    access: proxy
    uid: P8E80F9AEF21F7000
    url: http://jaeger:16686
    editable: true
    jsonData:
      tracesToLogsV2:
          datasourceUid: P8E80F9AEF21F6940
          spanStartTimeShift: '5m'
          spanEndTimeShift: '-5m'
          customQuery: true
          query: '{job=~ ".+"} |="$${__trace.traceId}"'