apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    uid: PBFA97CFB590B2093
    url: http://prometheus:9090
    isDefault: true
    access: proxy
    editable: true

  - name: Loki
    type: loki
    access: proxy
    uid: P8E80F9AEF21F6940
    url: http://loki:3100
    editable: true

  - name: Jeager
    type: jaeger
    access: proxy
    uid: P8E80F9AEF21F7000
    url: http://jaeger:16686
    editable: true